// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"kratos-timer/internal/biz"
	"kratos-timer/internal/conf"
	"kratos-timer/internal/data"
	"kratos-timer/internal/server"
	"kratos-timer/internal/service"

	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	timerRepo := data.NewTimerRepo(dataData)
	timerUsecase := biz.NewTimerUsecase(timerRepo)
	timerService := service.NewTimerService(timerUsecase)
	grpcServer := server.NewGRPCServer(confServer, timerService)
	httpServer := server.NewHTTPServer(confServer, timerService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
