// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: timer/v1/timer.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HttpParams 定时任务回调参数
type HttpParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpParams) Reset() {
	*x = HttpParams{}
	mi := &file_timer_v1_timer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpParams) ProtoMessage() {}

func (x *HttpParams) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_timer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpParams.ProtoReflect.Descriptor instead.
func (*HttpParams) Descriptor() ([]byte, []int) {
	return file_timer_v1_timer_proto_rawDescGZIP(), []int{0}
}

func (x *HttpParams) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpParams) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpParams) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpParams) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// TimerInfo 定时任务信息
type TimerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	App           string                 `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	Cron          string                 `protobuf:"bytes,4,opt,name=cron,proto3" json:"cron,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	HttpParams    *HttpParams            `protobuf:"bytes,6,opt,name=http_params,json=httpParams,proto3" json:"http_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerInfo) Reset() {
	*x = TimerInfo{}
	mi := &file_timer_v1_timer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerInfo) ProtoMessage() {}

func (x *TimerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_timer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerInfo.ProtoReflect.Descriptor instead.
func (*TimerInfo) Descriptor() ([]byte, []int) {
	return file_timer_v1_timer_proto_rawDescGZIP(), []int{1}
}

func (x *TimerInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TimerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TimerInfo) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *TimerInfo) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *TimerInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TimerInfo) GetHttpParams() *HttpParams {
	if x != nil {
		return x.HttpParams
	}
	return nil
}

// EnableTimerRequest 启用定时任务请求
type EnableTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableTimerRequest) Reset() {
	*x = EnableTimerRequest{}
	mi := &file_timer_v1_timer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableTimerRequest) ProtoMessage() {}

func (x *EnableTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_timer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableTimerRequest.ProtoReflect.Descriptor instead.
func (*EnableTimerRequest) Descriptor() ([]byte, []int) {
	return file_timer_v1_timer_proto_rawDescGZIP(), []int{2}
}

func (x *EnableTimerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnableTimerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DisableTimerRequest 禁用定时任务请求
type DisableTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableTimerRequest) Reset() {
	*x = DisableTimerRequest{}
	mi := &file_timer_v1_timer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableTimerRequest) ProtoMessage() {}

func (x *DisableTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_timer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableTimerRequest.ProtoReflect.Descriptor instead.
func (*DisableTimerRequest) Descriptor() ([]byte, []int) {
	return file_timer_v1_timer_proto_rawDescGZIP(), []int{3}
}

func (x *DisableTimerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DisableTimerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetTimerRequest 获取定时任务请求
type GetTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimerRequest) Reset() {
	*x = GetTimerRequest{}
	mi := &file_timer_v1_timer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimerRequest) ProtoMessage() {}

func (x *GetTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_timer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimerRequest.ProtoReflect.Descriptor instead.
func (*GetTimerRequest) Descriptor() ([]byte, []int) {
	return file_timer_v1_timer_proto_rawDescGZIP(), []int{4}
}

func (x *GetTimerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ListTimerRequest 获取定时任务列表请求
type ListTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimerRequest) Reset() {
	*x = ListTimerRequest{}
	mi := &file_timer_v1_timer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimerRequest) ProtoMessage() {}

func (x *ListTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_timer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimerRequest.ProtoReflect.Descriptor instead.
func (*ListTimerRequest) Descriptor() ([]byte, []int) {
	return file_timer_v1_timer_proto_rawDescGZIP(), []int{5}
}

func (x *ListTimerRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

// ListTimerReply 获取定时任务列表回复
type ListTimerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timers        []*TimerInfo           `protobuf:"bytes,1,rep,name=timers,proto3" json:"timers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimerReply) Reset() {
	*x = ListTimerReply{}
	mi := &file_timer_v1_timer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimerReply) ProtoMessage() {}

func (x *ListTimerReply) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_timer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimerReply.ProtoReflect.Descriptor instead.
func (*ListTimerReply) Descriptor() ([]byte, []int) {
	return file_timer_v1_timer_proto_rawDescGZIP(), []int{6}
}

func (x *ListTimerReply) GetTimers() []*TimerInfo {
	if x != nil {
		return x.Timers
	}
	return nil
}

var File_timer_v1_timer_proto protoreflect.FileDescriptor

const file_timer_v1_timer_proto_rawDesc = "" +
	"\n" +
	"\x14timer/v1/timer.proto\x12\fapi.timer.v1\x1a\x1cgoogle/api/annotations.proto\"\xc7\x01\n" +
	"\n" +
	"HttpParams\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12?\n" +
	"\aheaders\x18\x02 \x03(\v2%.api.timer.v1.HttpParams.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\tTimerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03app\x18\x03 \x01(\tR\x03app\x12\x12\n" +
	"\x04cron\x18\x04 \x01(\tR\x04cron\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x129\n" +
	"\vhttp_params\x18\x06 \x01(\v2\x18.api.timer.v1.HttpParamsR\n" +
	"httpParams\"8\n" +
	"\x12EnableTimerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"9\n" +
	"\x13DisableTimerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"!\n" +
	"\x0fGetTimerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x10ListTimerRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\"A\n" +
	"\x0eListTimerReply\x12/\n" +
	"\x06timers\x18\x01 \x03(\v2\x17.api.timer.v1.TimerInfoR\x06timers2\xf8\x03\n" +
	"\x05Timer\x12V\n" +
	"\vCreateTimer\x12\x17.api.timer.v1.TimerInfo\x1a\x17.api.timer.v1.TimerInfo\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/timers\x12k\n" +
	"\vEnableTimer\x12 .api.timer.v1.EnableTimerRequest\x1a\x17.api.timer.v1.TimerInfo\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/timers/{id}/enable\x12n\n" +
	"\fDisableTimer\x12!.api.timer.v1.DisableTimerRequest\x1a\x17.api.timer.v1.TimerInfo\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/timers/{id}/disable\x12[\n" +
	"\bGetTimer\x12\x1d.api.timer.v1.GetTimerRequest\x1a\x17.api.timer.v1.TimerInfo\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/timers/{id}\x12]\n" +
	"\tListTimer\x12\x1e.api.timer.v1.ListTimerRequest\x1a\x1c.api.timer.v1.ListTimerReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/timersB\x1eZ\x1ckratos-timer/api/timer/v1;v1b\x06proto3"

var (
	file_timer_v1_timer_proto_rawDescOnce sync.Once
	file_timer_v1_timer_proto_rawDescData []byte
)

func file_timer_v1_timer_proto_rawDescGZIP() []byte {
	file_timer_v1_timer_proto_rawDescOnce.Do(func() {
		file_timer_v1_timer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_timer_v1_timer_proto_rawDesc), len(file_timer_v1_timer_proto_rawDesc)))
	})
	return file_timer_v1_timer_proto_rawDescData
}

var file_timer_v1_timer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_timer_v1_timer_proto_goTypes = []any{
	(*HttpParams)(nil),          // 0: api.timer.v1.HttpParams
	(*TimerInfo)(nil),           // 1: api.timer.v1.TimerInfo
	(*EnableTimerRequest)(nil),  // 2: api.timer.v1.EnableTimerRequest
	(*DisableTimerRequest)(nil), // 3: api.timer.v1.DisableTimerRequest
	(*GetTimerRequest)(nil),     // 4: api.timer.v1.GetTimerRequest
	(*ListTimerRequest)(nil),    // 5: api.timer.v1.ListTimerRequest
	(*ListTimerReply)(nil),      // 6: api.timer.v1.ListTimerReply
	nil,                         // 7: api.timer.v1.HttpParams.HeadersEntry
}
var file_timer_v1_timer_proto_depIdxs = []int32{
	7, // 0: api.timer.v1.HttpParams.headers:type_name -> api.timer.v1.HttpParams.HeadersEntry
	0, // 1: api.timer.v1.TimerInfo.http_params:type_name -> api.timer.v1.HttpParams
	1, // 2: api.timer.v1.ListTimerReply.timers:type_name -> api.timer.v1.TimerInfo
	1, // 3: api.timer.v1.Timer.CreateTimer:input_type -> api.timer.v1.TimerInfo
	2, // 4: api.timer.v1.Timer.EnableTimer:input_type -> api.timer.v1.EnableTimerRequest
	3, // 5: api.timer.v1.Timer.DisableTimer:input_type -> api.timer.v1.DisableTimerRequest
	4, // 6: api.timer.v1.Timer.GetTimer:input_type -> api.timer.v1.GetTimerRequest
	5, // 7: api.timer.v1.Timer.ListTimer:input_type -> api.timer.v1.ListTimerRequest
	1, // 8: api.timer.v1.Timer.CreateTimer:output_type -> api.timer.v1.TimerInfo
	1, // 9: api.timer.v1.Timer.EnableTimer:output_type -> api.timer.v1.TimerInfo
	1, // 10: api.timer.v1.Timer.DisableTimer:output_type -> api.timer.v1.TimerInfo
	1, // 11: api.timer.v1.Timer.GetTimer:output_type -> api.timer.v1.TimerInfo
	6, // 12: api.timer.v1.Timer.ListTimer:output_type -> api.timer.v1.ListTimerReply
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_timer_v1_timer_proto_init() }
func file_timer_v1_timer_proto_init() {
	if File_timer_v1_timer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_timer_v1_timer_proto_rawDesc), len(file_timer_v1_timer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timer_v1_timer_proto_goTypes,
		DependencyIndexes: file_timer_v1_timer_proto_depIdxs,
		MessageInfos:      file_timer_v1_timer_proto_msgTypes,
	}.Build()
	File_timer_v1_timer_proto = out.File
	file_timer_v1_timer_proto_goTypes = nil
	file_timer_v1_timer_proto_depIdxs = nil
}
