// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: timer/v1/timer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Timer_CreateTimer_FullMethodName  = "/api.timer.v1.Timer/CreateTimer"
	Timer_EnableTimer_FullMethodName  = "/api.timer.v1.Timer/EnableTimer"
	Timer_DisableTimer_FullMethodName = "/api.timer.v1.Timer/DisableTimer"
	Timer_GetTimer_FullMethodName     = "/api.timer.v1.Timer/GetTimer"
	Timer_ListTimer_FullMethodName    = "/api.timer.v1.Timer/ListTimer"
)

// TimerClient is the client API for Timer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimerClient interface {
	CreateTimer(ctx context.Context, in *TimerInfo, opts ...grpc.CallOption) (*TimerInfo, error)
	EnableTimer(ctx context.Context, in *EnableTimerRequest, opts ...grpc.CallOption) (*TimerInfo, error)
	DisableTimer(ctx context.Context, in *DisableTimerRequest, opts ...grpc.CallOption) (*TimerInfo, error)
	GetTimer(ctx context.Context, in *GetTimerRequest, opts ...grpc.CallOption) (*TimerInfo, error)
	ListTimer(ctx context.Context, in *ListTimerRequest, opts ...grpc.CallOption) (*ListTimerReply, error)
}

type timerClient struct {
	cc grpc.ClientConnInterface
}

func NewTimerClient(cc grpc.ClientConnInterface) TimerClient {
	return &timerClient{cc}
}

func (c *timerClient) CreateTimer(ctx context.Context, in *TimerInfo, opts ...grpc.CallOption) (*TimerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerInfo)
	err := c.cc.Invoke(ctx, Timer_CreateTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerClient) EnableTimer(ctx context.Context, in *EnableTimerRequest, opts ...grpc.CallOption) (*TimerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerInfo)
	err := c.cc.Invoke(ctx, Timer_EnableTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerClient) DisableTimer(ctx context.Context, in *DisableTimerRequest, opts ...grpc.CallOption) (*TimerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerInfo)
	err := c.cc.Invoke(ctx, Timer_DisableTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerClient) GetTimer(ctx context.Context, in *GetTimerRequest, opts ...grpc.CallOption) (*TimerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerInfo)
	err := c.cc.Invoke(ctx, Timer_GetTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerClient) ListTimer(ctx context.Context, in *ListTimerRequest, opts ...grpc.CallOption) (*ListTimerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTimerReply)
	err := c.cc.Invoke(ctx, Timer_ListTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimerServer is the server API for Timer service.
// All implementations must embed UnimplementedTimerServer
// for forward compatibility.
type TimerServer interface {
	CreateTimer(context.Context, *TimerInfo) (*TimerInfo, error)
	EnableTimer(context.Context, *EnableTimerRequest) (*TimerInfo, error)
	DisableTimer(context.Context, *DisableTimerRequest) (*TimerInfo, error)
	GetTimer(context.Context, *GetTimerRequest) (*TimerInfo, error)
	ListTimer(context.Context, *ListTimerRequest) (*ListTimerReply, error)
	mustEmbedUnimplementedTimerServer()
}

// UnimplementedTimerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimerServer struct{}

func (UnimplementedTimerServer) CreateTimer(context.Context, *TimerInfo) (*TimerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTimer not implemented")
}
func (UnimplementedTimerServer) EnableTimer(context.Context, *EnableTimerRequest) (*TimerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableTimer not implemented")
}
func (UnimplementedTimerServer) DisableTimer(context.Context, *DisableTimerRequest) (*TimerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableTimer not implemented")
}
func (UnimplementedTimerServer) GetTimer(context.Context, *GetTimerRequest) (*TimerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimer not implemented")
}
func (UnimplementedTimerServer) ListTimer(context.Context, *ListTimerRequest) (*ListTimerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTimer not implemented")
}
func (UnimplementedTimerServer) mustEmbedUnimplementedTimerServer() {}
func (UnimplementedTimerServer) testEmbeddedByValue()               {}

// UnsafeTimerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimerServer will
// result in compilation errors.
type UnsafeTimerServer interface {
	mustEmbedUnimplementedTimerServer()
}

func RegisterTimerServer(s grpc.ServiceRegistrar, srv TimerServer) {
	// If the following call panics, it indicates UnimplementedTimerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Timer_ServiceDesc, srv)
}

func _Timer_CreateTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServer).CreateTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Timer_CreateTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServer).CreateTimer(ctx, req.(*TimerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timer_EnableTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServer).EnableTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Timer_EnableTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServer).EnableTimer(ctx, req.(*EnableTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timer_DisableTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServer).DisableTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Timer_DisableTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServer).DisableTimer(ctx, req.(*DisableTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timer_GetTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServer).GetTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Timer_GetTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServer).GetTimer(ctx, req.(*GetTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timer_ListTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServer).ListTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Timer_ListTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServer).ListTimer(ctx, req.(*ListTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Timer_ServiceDesc is the grpc.ServiceDesc for Timer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Timer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.timer.v1.Timer",
	HandlerType: (*TimerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTimer",
			Handler:    _Timer_CreateTimer_Handler,
		},
		{
			MethodName: "EnableTimer",
			Handler:    _Timer_EnableTimer_Handler,
		},
		{
			MethodName: "DisableTimer",
			Handler:    _Timer_DisableTimer_Handler,
		},
		{
			MethodName: "GetTimer",
			Handler:    _Timer_GetTimer_Handler,
		},
		{
			MethodName: "ListTimer",
			Handler:    _Timer_ListTimer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timer/v1/timer.proto",
}
