// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: timer/v1/timer.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationTimerCreateTimer = "/api.timer.v1.Timer/CreateTimer"
const OperationTimerDisableTimer = "/api.timer.v1.Timer/DisableTimer"
const OperationTimerEnableTimer = "/api.timer.v1.Timer/EnableTimer"
const OperationTimerGetTimer = "/api.timer.v1.Timer/GetTimer"
const OperationTimerListTimer = "/api.timer.v1.Timer/ListTimer"

type TimerHTTPServer interface {
	CreateTimer(context.Context, *TimerInfo) (*TimerInfo, error)
	DisableTimer(context.Context, *DisableTimerRequest) (*TimerInfo, error)
	EnableTimer(context.Context, *EnableTimerRequest) (*TimerInfo, error)
	GetTimer(context.Context, *GetTimerRequest) (*TimerInfo, error)
	ListTimer(context.Context, *ListTimerRequest) (*ListTimerReply, error)
}

func RegisterTimerHTTPServer(s *http.Server, srv TimerHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/timers", _Timer_CreateTimer0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/timers/{id}/enable", _Timer_EnableTimer0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/timers/{id}/disable", _Timer_DisableTimer0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/timers/{id}", _Timer_GetTimer0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/timers", _Timer_ListTimer0_HTTP_Handler(srv))
}

func _Timer_CreateTimer0_HTTP_Handler(srv TimerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TimerInfo
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTimerCreateTimer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTimer(ctx, req.(*TimerInfo))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TimerInfo)
		return ctx.Result(200, reply)
	}
}

func _Timer_EnableTimer0_HTTP_Handler(srv TimerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnableTimerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTimerEnableTimer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnableTimer(ctx, req.(*EnableTimerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TimerInfo)
		return ctx.Result(200, reply)
	}
}

func _Timer_DisableTimer0_HTTP_Handler(srv TimerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DisableTimerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTimerDisableTimer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DisableTimer(ctx, req.(*DisableTimerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TimerInfo)
		return ctx.Result(200, reply)
	}
}

func _Timer_GetTimer0_HTTP_Handler(srv TimerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTimerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTimerGetTimer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTimer(ctx, req.(*GetTimerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TimerInfo)
		return ctx.Result(200, reply)
	}
}

func _Timer_ListTimer0_HTTP_Handler(srv TimerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTimerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTimerListTimer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTimer(ctx, req.(*ListTimerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTimerReply)
		return ctx.Result(200, reply)
	}
}

type TimerHTTPClient interface {
	CreateTimer(ctx context.Context, req *TimerInfo, opts ...http.CallOption) (rsp *TimerInfo, err error)
	DisableTimer(ctx context.Context, req *DisableTimerRequest, opts ...http.CallOption) (rsp *TimerInfo, err error)
	EnableTimer(ctx context.Context, req *EnableTimerRequest, opts ...http.CallOption) (rsp *TimerInfo, err error)
	GetTimer(ctx context.Context, req *GetTimerRequest, opts ...http.CallOption) (rsp *TimerInfo, err error)
	ListTimer(ctx context.Context, req *ListTimerRequest, opts ...http.CallOption) (rsp *ListTimerReply, err error)
}

type TimerHTTPClientImpl struct {
	cc *http.Client
}

func NewTimerHTTPClient(client *http.Client) TimerHTTPClient {
	return &TimerHTTPClientImpl{client}
}

func (c *TimerHTTPClientImpl) CreateTimer(ctx context.Context, in *TimerInfo, opts ...http.CallOption) (*TimerInfo, error) {
	var out TimerInfo
	pattern := "/v1/timers"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTimerCreateTimer),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TimerHTTPClientImpl) DisableTimer(ctx context.Context, in *DisableTimerRequest, opts ...http.CallOption) (*TimerInfo, error) {
	var out TimerInfo
	pattern := "/v1/timers/{id}/disable"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTimerDisableTimer),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TimerHTTPClientImpl) EnableTimer(ctx context.Context, in *EnableTimerRequest, opts ...http.CallOption) (*TimerInfo, error) {
	var out TimerInfo
	pattern := "/v1/timers/{id}/enable"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTimerEnableTimer),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TimerHTTPClientImpl) GetTimer(ctx context.Context, in *GetTimerRequest, opts ...http.CallOption) (*TimerInfo, error) {
	var out TimerInfo
	pattern := "/v1/timers/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTimerGetTimer),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TimerHTTPClientImpl) ListTimer(ctx context.Context, in *ListTimerRequest, opts ...http.CallOption) (*ListTimerReply, error) {
	var out ListTimerReply
	pattern := "/v1/timers"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTimerListTimer),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
